выполнил второе задание
htmlacademy-htmlcss/1779275-sedona-31 pull request #2
Opened 2021-05-23 15:37 UTC by Pavel1989-03

2021-05-23 21:28 UTC, SidSpears69 requested changes

2021-05-23 21:28 UTC, SidSpears69 commented on index.html
> +      <h2>Седона — небольшой городок в Аризоне, заслуживающий большего!</h2>
Объединить в один заголовок h2

2021-05-23 21:28 UTC, SidSpears69 commented on index.html
> +      <h3>Там есть
В заголовки нельзя вставлять "p"

2021-05-23 21:28 UTC, SidSpears69 commented on index.html
> +  <selecton>
Нет такого тега

2021-05-23 21:28 UTC, SidSpears69 commented on index.html
> +   <p>
Заголовки в p вкладывать тоже нельзя, отсутствует тег form

2021-05-23 21:28 UTC, SidSpears69 commented on index.html
> +    <p>
В целом тег p не подходит для создания контейнеров, это параграф, для контейнеров можно использовать div, в формах fieldset

2021-05-23 21:28 UTC, SidSpears69 commented on index.html
> +      <button type="button">
Отформатируй код, не очень удобно читать

2021-05-23 21:28 UTC, SidSpears69 commented on index.html
> + <footer>
Футер вынести из main

2021-05-23 21:28 UTC, SidSpears69 commented on index.html
> + <selection>
Несуществующий тег

2021-05-23 21:28 UTC, SidSpears69 commented on index.html
> + <selection>
То же самое

2021-05-24 10:48 UTC, Pavel1989-03 commented
исправил ошибки

2021-05-26 18:06 UTC, Pavel1989-03 commented
исправляет ошибки

2021-05-26 18:08 UTC, Pavel1989-03 commented
исправил

2021-05-26 22:10 UTC, merged